version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/app
      - nuxt-project-node_modules:/app/nuxt-project/node_modules
      - storybook-project-node_modules:/app/storybook-project/node_modules
    ports:
      - 3000:3000
      - 8000:8000
    
volumes:
  nuxt-project-node_modules: {}
  storybook-project-node_modules: {}
